Adding tagging based on request context
pjcalvo/locust-influxdb-listener pull request #16
Opened 2022-07-18 21:49 UTC by jmfiola

if someone now does something like: `locustClient.get('asdf.com/get', context={'environment':'prod'})`, then that `environment` tag will be added for that request when it is reported to influxdb. This allows us to do more granular filtering once we want to query that influxdb data.

There were also some linting changes that my Pycharm decided to do. I can get rid of those if you want! Thanks.

2022-07-18 21:50 UTC, jmfiola commented
@pjcalvo FYI

2022-07-19 20:24 UTC, pjcalvo commented
Will Merge and release tomorrow. Thanks for doing this.

2022-07-19 20:40 UTC, pjcalvo requested changes
Please check the changes

2022-07-19 20:40 UTC, pjcalvo commented on example/requirements.txt
> +locust_influxdb_listener == 0.0.6
This will be version 0.0.7 after my release. So no need to increase this for now.

2022-07-19 20:40 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +        if response:
This is confusing, it is not clear why the else always set the response to True. I think doing something like the following will be cleaner:

```
was_successful = True
if response:
            # override with response code
            was_successful = 199 < response.status_code < 400
```

2022-07-20 15:06 UTC, jmfiola commented on example/requirements.txt
> +locust_influxdb_listener == 0.0.6
reverted

2022-07-20 15:19 UTC, jmfiola commented on locust_influxdb_listener/__init__.py
> +        if response:
changed

2022-07-20 15:21 UTC, jmfiola commented
> 

I reverted almost all the formatting changes that my IDE was suggesting. There's a few pesky ones that it really wants me to do though..

Yes, the increase in the locust version is mandatory due to us now using the request hook instead of request_success and request_failure

2022-07-21 18:20 UTC, pjcalvo commented
Awesome, I will take another look. Would you mind adding the required version somewhere in the top of the README.md file? Thanks

2022-07-21 19:42 UTC, pjcalvo commented
> 

So I checked locust logs and indeed the on_failure and on_success events are deprecated and will be removed soon, but the requests hook has been out since version 1.5.0 and not on 2.8.0 like this PR is suggesting. I will check if we can go back to 1.5.0 with success and then leave that version.

I would hate to force users to use upgrade to 2.8.0 for a feature that has been out since previous versions.

https://github.com/locustio/locust/releases/tag/1.5.0

2022-08-01 14:32 UTC, jmfiola commented
@pjcalvo Changes have been made to versions and README as requested. Sorry this was a little late, I was on vacation!

2022-08-04 09:49 UTC, pjcalvo requested changes

2022-08-04 09:49 UTC, pjcalvo commented on example/README.md
> +LocustIO base project with a custom influxDB listener. This package requires that Locust v1.5.0 or greater.
```suggestion
LocustIO base project with a custom influxDB listener. This package requires Locust v1.5.0 or greater.
```

2022-08-04 09:50 UTC, pjcalvo commented
Nice thanks. I was also on holiday. One more small change and we are ready to release this version.

2022-08-04 13:43 UTC, jmfiola commented
> Nice thanks. I was also on holiday. One more small change and we are ready to release this version.

No worries! Change made. Thank you.

2022-08-04 15:14 UTC, pjcalvo approved these changes

2022-08-04 15:14 UTC, merged