Add support for user count over time
pjcalvo/locust-influxdb-listener pull request #17
Opened 2023-02-23 17:09 UTC by jmfiola

This MR adds the "user_count" field to all locust requests

2023-02-23 17:09 UTC, jmfiola commented
@pjcalvo FYI

2023-02-27 19:38 UTC, pjcalvo requested changes

2023-02-27 19:38 UTC, pjcalvo commented on setup.py
I will increase the version when releasing. So this PR should just focus on the change.

2023-02-27 19:38 UTC, pjcalvo commented on example/requirements.txt
> +locust_influxdb_listener == 0.0.9
Please also remove the version here.

2023-02-27 19:40 UTC, pjcalvo commented
Hey thanks for doing this PR. A couple of things: The change on the dashboard json is way to big to review. Can u put that on a separate PR, add a more descriptive explanation or attach some screenshots.

Also please remove the increase version. I will increase the version manually when creating a new release tag.

Thanksm

2023-02-27 22:09 UTC, jmfiola commented on setup.py
reverted

2023-02-27 22:09 UTC, jmfiola commented on example/requirements.txt
> +locust_influxdb_listener == 0.0.9
reverted

2023-02-27 22:10 UTC, jmfiola commented
> 

Done! No problem, happy to contribute.

2023-03-08 18:10 UTC, jmfiola commented
@pjcalvo Looking for another review here

2023-03-08 18:40 UTC, pjcalvo approved these changes

2023-03-08 18:40 UTC, merged

2023-03-08 18:41 UTC, pjcalvo commented
Thanks, sorry it took me a while to review it.