refactoring, add types
pjcalvo/locust-influxdb-listener pull request #24
Opened 2023-09-26 10:31 UTC by issamansur

refactor #19 
Please, check all very carefully

2023-09-26 11:45 UTC, pjcalvo requested changes

2023-09-26 11:45 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +        # Catching too general exception.
I agree but at this point the exception could be caused either the user sent wrong information or influxDB connection failed, which would be logged and let to the user to fix...

2023-09-26 11:45 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +    def test_stop(self, user_count: int = 0, environment: any = None) -> None:
use this import instead:

```
from locust.env import Environment
```

and this can be typed to `Environment`

2023-09-26 11:45 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +            user_instance: locust.User,
Use an import to handle this type:
```
from locust import User
```

user_instance: User,

2023-09-26 12:10 UTC, issamansur commented
Done!

2023-09-26 13:46 UTC, issamansur commented
What can we use? `Response` or `HTTPConnectionPool`?

2023-09-26 14:00 UTC, pjcalvo requested changes

2023-09-26 14:00 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +            response: Response | HTTPConnectionPool, # need review
Apologies I didn't see this note as first. 

We should leave this as `any` since the request response depends on the library used. LocustIO by default uses `requests` library, but we can override that and the response object would be whatever we choose from the different library.. 

So none.

2023-09-26 14:00 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +            response: Response | HTTPConnectionPool, # need review
We are currently using `requests.Response` in this library, as in the `status_code` property. So thinking better about it we can leave Response and I will open a PR to make sure this is more generic.

Thanks,

2023-09-26 14:08 UTC, issamansur commented on locust_influxdb_listener/__init__.py
> +            response: Response | HTTPConnectionPool, # need review
Well, then... change the type of `response` to `any` for now?

2023-09-26 14:16 UTC, issamansur commented on locust_influxdb_listener/__init__.py
> +            response: Response | HTTPConnectionPool, # need review
I apologize for the lack of professionalism

2023-09-26 14:20 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +            response: Response | HTTPConnectionPool, # need review
Perfect. And no need to apologize.

2023-09-26 14:34 UTC, issamansur commented
Done!

2023-09-26 14:41 UTC, pjcalvo requested changes

2023-09-26 14:41 UTC, pjcalvo commented on locust_influxdb_listener/__init__.py
> +            user_instance: any,
I just realised this has to be `User` as well. 

:)

2023-09-26 14:46 UTC, issamansur commented
Done! I would be glad to hear any recommendations on pool requests from you)

2023-09-27 12:01 UTC, issamansur commented
Build failed on python version 3.11 because type of variable cannot defined by symbol `|`, for example: `int | str`.
What can I do with this?

2023-09-27 12:09 UTC, pjcalvo commented
> Build failed on python version 3.11 because type of variable cannot defined by symbol `|`, for example: `int | str`. What can I do with this?

Please use union which is supported in python 3.9

```
from typing import Union

# Define a variable that can be either int or str
variable: Union[int, str]
```

2023-09-27 12:21 UTC, issamansur commented
Done!

2023-10-04 13:21 UTC, issamansur commented
@pjcalvo meow)

2023-10-04 13:42 UTC, pjcalvo approved these changes

2023-10-04 13:42 UTC, merged